import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { SignOutButton, useAuth, useUser } from "@clerk/nextjs";

import { api } from "y/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const { isSignedIn, user } = useUser();
  const { isLoaded, userId, sessionId, getToken } = useAuth();

  const Loading = <>loading...</>;

  return (
    <>
      {!isLoaded ? (
        Loading
      ) : (
        <>
          <Head>
            <title>Twitter clone App</title>
            <meta name="description" content="Generated by create-t3-app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
            <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
              <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
                Welcome to my <span className="text-[hsl(280,100%,70%)]">Twitter Clone</span> App
              </h1>
              <div className="text-2xl text-white">
                {isSignedIn && <h1>Hello {user.username}</h1>}
              </div>

              <div>
                <SignOutButton />
              </div>
            </div>
          </main>
        </>
      )}
    </>
  );
};

export default Home;
